services:
  # 🗄️ MongoDB Database
  mongo:
    image: mongo:latest
    container_name: studynotion-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: studynotion-mongo
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  # ⚙️ Backend Service
  backend:
    build:
      context: ./backend
    container_name: studynotion-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo



  # 🌐 Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: studynotion-frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongo-data:
